name: Deploy Static HTML to GitHub Pages

on:
  push:
    branches:
      - main  # Workflow ini akan dijalankan ketika ada push ke branch 'main'

permissions:
  contents: write  # Memberikan izin untuk menulis ke repo (branch gh-pages)

jobs:
  deploy:
    runs-on: ubuntu-latest  # Workflow ini berjalan di Ubuntu

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Mengambil semua file di repo

      - name: Deploy ke GitHub Pages
        uses: peaceiris/actions-gh-pages@v3  # Menggunakan action untuk deploy ke GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token untuk otentikasi otomatis
          publish_dir: ./  # Deploy file dari folder root repo (di mana index.html berada)
